### ISSUE TITLE
Info about mounting the toolhead PCB for SBCW2 missing from Voron 2.4 Build Notes

### ISSUE THREAD

**Issue by Carl-Wilhelm** [MotorDynamicsLab/LDOVoron2#10]
There should be a note that links to the [LDO Toolhead Wiring Kit](https://docs.ldomotors.com/en/voron/toolhead_harness) from the [Build Notes/FAQ](https://docs.ldomotors.com/en/voron/voron2/build-faq) section. I spent a LOT of time trying to figure out how to use the Toolhead PCB that came with the LDO kit before i stumbled upon that link.

**Comment by camerony** [comment]
Thank for the feedback.  I've added a link.
