### ISSUE TITLE
Misaligned slot in in LDO SB2 CW2 PCB spacer

### ISSUE THREAD

**Issue by jagerman** [MotorDynamicsLab/LDOVoron2#11]
I printed the CW2 PCB spacer, but the slot to accommodate the soldered pins doesn't line up with the pins on the PCB that came with my LDO Trident kit.  I had to modify it to move to slow towards the flat-head screw hole to make it work.  (Photo incoming).

**Comment by jagerman** [comment]
![image](https://user-images.githubusercontent.com/4459524/213924996-e14a3a79-989b-4e4a-9022-c05a2c2c155b.png)

I had to modify the part to move to slot towards the side with the nut to make it work.

**Comment by camerony** [comment]
fixed
