### ISSUE TITLE
Purge bucket files don't include mounting bracket

### ISSUE THREAD

**Issue by maxim-kukushkin** [MotorDynamicsLab/LDOVoron2#12]
The assembly instructions indicate that it's possible to build a purge bucket with a brush holder using the materials provided in the kit. There're also custom files under STLs/PurgeBucket to accommodate the taller heatbed.

However, it doesn't include anything for mounting the purge bucket. The original [extension bracket](https://github.com/VoronDesign/VoronUsers/blob/master/orphaned_mods/printer_mods/edwardyeeks/Decontaminator_Purge_Bucket_%26_Nozzle_Scrubber/STLs/extension_bracket_v1.8_rev4.stl) doesn't seem to be applicable to the provided architecture of Voron Trident (the photos there show a completely different gantry).

It also doesn't seems possible to find a bracket in any other available sources.

So photos or alternative STLs would be very much appreciated

**Comment by cr0Kz** [comment]
> The assembly instructions indicate that it's possible to build a purge bucket with a brush holder using the materials provided in the kit. There're also custom files under STLs/PurgeBucket to accommodate the taller heatbed.
> 
> However, it doesn't include anything for mounting the purge bucket. The original [extension bracket](https://github.com/VoronDesign/VoronUsers/blob/master/orphaned_mods/printer_mods/edwardyeeks/Decontaminator_Purge_Bucket_%26_Nozzle_Scrubber/STLs/extension_bracket_v1.8_rev4.stl) doesn't seem to be applicable to the provided architecture of Voron Trident (the photos there show a completely different gantry).
> 
> It also doesn't seems possible to find a bracket in any other available sources.
> 
> So photos or alternative STLs would be very much appreciated

I ended up using this version instead [Trident mount for Decontaminator Purge Bucket & Nozzle Scrubber](https://www.printables.com/model/174526-trident-mount-for-decontaminator-purge-bucket-nozz).

I am trying to tweak the macro now. I will reply to this issue once I figure it out.

**Comment by torndar** [comment]
About to try to print and install this. Did you get things figured out?

It looks like I should print these 3 for the LDO Voron Trident kit
- https://www.printables.com/model/174526-trident-mount-for-decontaminator-purge-bucket-nozz
- https://github.com/MotorDynamicsLab/LDOVoron2/blob/main/STLs/Purge%20Bucket/brush_holder_sheet_stop.stl
- https://github.com/VoronDesign/VoronUsers/blob/master/orphaned_mods/printer_mods/edwardyeeks/Decontaminator_Purge_Bucket_%26_Nozzle_Scrubber/STLs/purge_bucket_250mm_rev4.stl (maybe the 300mm version of this one?)

**Comment by torndar** [comment]
For the record the 3 models I linked above worked. However, the bucket was rather loose, even after putting magnets in it, so I added foam to the inner edges to pad between the bracket arm and the bucket. That seems to be working pretty well.
