### ISSUE TITLE
Issue with bolt clearence LDOSBCW2Cover.step

### ISSUE THREAD

**Issue by Carl-Wilhelm** [MotorDynamicsLab/LDOVoron2#9]
The button head bolts hits the "chamfer" on the side of the hole. The clearance on the official Voron parts is about 0,3-0,5mm larger.
Se attached picture.
![ClockWork](https://user-images.githubusercontent.com/75078972/204809536-f4a59cc9-e602-4c98-84d7-9e6c0c8403b3.png)

Also the hole is oval in the CAD file and should be corrected.

See differences in CAD files:
![cable_door_for_pcb](https://user-images.githubusercontent.com/75078972/204810813-fd86ddb8-3dfb-4998-838f-2c2dd3e4d98d.png)
![LDOSBCW2Cover](https://user-images.githubusercontent.com/75078972/204810816-9e6a4510-5f57-4760-8423-af7e23f493f2.png)

**Comment by camerony** [comment]
Thanks for the feedback.  I'll look into this.

**Comment by camerony** [comment]
This now deprecated.
